### ISSUE TITLE
No background jobs indication?

### ISSUE THREAD

**Issue by gbrlsnchs** [tylerreckart/hyperzsh#23]
**Is your feature request related to a problem? Please describe.**
README says it shows whether there are background jobs running, but I didn't find it in source neither was able to activate it anywhere else.

**Describe the solution you'd like**
Implement it somehow, I could send a PR but I wanted to be sure it indeed not implemented.

**Describe alternatives you've considered**
I'm not an expert, so I would do what Agnoster does, that is count how many running jobs there are via `jobs -l | wc -l`.

**Additional context**
N/A.

**Comment by tylerreckart** [comment]
Thank you for bringing this to my attention. Background jobs were part of the original release of the theme but that functionality has been removed in subsequent versions. The README has been updated to reflect the current functionality.
