### ISSUE TITLE
Suspend on multipass

### ISSUE THREAD

**Issue by FourLeafTec** [tylerreckart/hyperzsh#25]
I have a directory /Volumes/data/openwrt clone from https://github.com/openwrt/openwrt on macOS
then mount the directory into multipass ubuntu-lts(20) and cd ~/data/openwrt
now zsh suspended.

0. open shell on macOS
1. cd /Volumes/data
2. git clone https://github.com/openwrt/openwrt
3. brew install multipass
4. multipass lauch ubuntu-lts
5. multipass mount /Volumes/data ubuntu:/home/ubuntu/data
6. multipass shell ubuntu-lts
7. sudo apt install zsh
8. install antigen
9. install hyperzsh theme
10. cd /home/ubuntu/data/openwrt

then zsh well suspended and Ctrl-C can't stop this cd command

**Screenshots**
![截屏2020-10-16 上午10 27 05](https://user-images.githubusercontent.com/5875432/96206389-5d9f4a80-0f9b-11eb-8964-c80830270807.png)

**Additional context**
It is only can trigger with openwrt git repository.
if I make a git repository such as test_git and commit to github,it's ok.
It is very strange,maybe mast use a big git repository

It is only can trigger on ubuntu image,on macOS host,it's ok.

**Comment by tylerreckart** [comment]
@FourLeafTec Thanks for opening this issue! From what you've outlined I do suspect that this is related to a memory issue in large repositories. I'll do some investigation and see if I can optimize behavior.
