### ISSUE TITLE
Show latest sha?

### ISSUE THREAD

**Issue by pertrai1** [tylerreckart/hyperzsh#5]
I really like this. Is there any way to show the latest short sha? would really be awesome to have this.

**Comment by tylerreckart** [comment]
Interesting thought. There isn't any way to view the sha at the moment, but I'll open up a branch and get the feature in the works.

**Comment by tylerreckart** [comment]
@pertrai1 Added support and updated the documentation for you 😄

**Comment by pertrai1** [comment]
@tylerreckart Loving It!! Thank you
