### ISSUE TITLE
Spacing between SHA and Time

### ISSUE THREAD

**Issue by pertrai1** [tylerreckart/hyperzsh#6]
Thank you for adding the SHA. Do not know how to handle this situation where the SHA has no space between it and the time:

![sha-time](https://cloud.githubusercontent.com/assets/442374/21743693/80bb9848-d4d5-11e6-8ce9-edde23e28763.png)

**Comment by tylerreckart** [comment]
Oh that's my bad. Meant to add in the spacing in the declaration. Just updated it. I have the space in my prompt, but if you're still having issues, try playing around with the spacing in the declarations on lines 28 and 29.
