### ISSUE TITLE
Spacing Between Prompt and Input

### ISSUE THREAD

**Issue by elithrar** [tylerreckart/hyperzsh#7]
When adding this theme to oh-my-zsh, the spacing between the prompt and input is lost on subsequent commands:

![losesthespace](https://cloud.githubusercontent.com/assets/18544/22553413/7538c4be-e911-11e6-8cff-f252f12eb427.gif)

-- Meta

> OS version and name: macOS 10.12 (16A323)
> Hyper.app version: Version 1.1.0 (1.1.0.1408)
> Link of a Gist with the contents of your .hyper.js: https://gist.github.com/elithrar/fd41632ccfe22ee1bc5f7ad1a952a748
> Relevant information from devtools N/A

**Comment by tylerreckart** [comment]
Interesting. I'm running the theme on oh-my-zsh as well and I've never run across that issue. Looking into it.

**Comment by elithrar** [comment]
Thanks! Removing all plugins and quit -> re-launching doesn't seem to fix.

**Comment by tylerreckart** [comment]
@elithrar I apologize for the late response, but I haven't been able to track down what is causing your issue. Have you edited `hyperzsh.zsh-theme` at all? If so, can you link to a gist?

**Comment by tylerreckart** [comment]
Closed due to inactivity
