### ISSUE TITLE
How to set $PROMPT

### ISSUE THREAD

**Issue by artivilla** [tylerreckart/hyperzsh#9]
Tried installing hyperzsh using antigen, here's my .zshrc file:
```
# antigen
source /usr/local/share/antigen/antigen.zsh

# install some antigen bundles
local b="antigen-bundle"

# anitgen hyper theme
$b tylerreckart/hyperzsh
```
I also uncommented the second prompt to get the SHA.
My prompt is set to something else but I can't tell where. There is no .bash_profile, .bash files set.

https://cloudup.com/cApdUem8fqA

**Comment by desyncr** [comment]
@artivilla `antigen theme tylerreckart/hyperzsh hyperzsh.zsh-theme`

**Comment by artivilla** [comment]
@desyncr thank you! works perf. 🙂
